### ISSUE TITLE
Change "View Source" on hover to "Link" and "Source"

### ISSUE THREAD

**Issue by dstillman** [zotero/styles-repo#23]
With the former triggering `?q=id:apa`.

Follow-up to #11

**Comment by dstillman** [comment]
This is now live. (Might require a force-reload if you've visited recently.)

**Comment by rmzelle** [comment]
Thanks.

Would a link icon (e.g. https://octicons.github.com/icon/link/, which GitHub uses when hovering over anchored headers, e.g. https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#guide-to-submitting-csl-styles-and-csl-locales) be any clearer than "Link"?

I also felt a slight shudder because hovering over a "Link" link doesn't show the target URL (like any regular link does in Chrome). Would it be possible to add a "href" attribute to them? That would also make it possible to go use the browser's back button to deselect a style.

**Comment by dstillman** [comment]
Yeah, I agree on both.

**Comment by rmzelle** [comment]
Great. ("Link" is a bit confusing, since the left-most installation/download URLs also look like regular links)
